### ISSUE TITLE
Need useful error messages when database is invalid

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#30]
@pdigiglio @wilhelma 

I am trying to test my tool by running on Parceive on a variety of databases. For some of these databases, Parceive does not do anything - it completes without any print statements from my tool, which means it is not generating any events. I am assuming this is because the database inputs I am giving it are somehow invalid.

Can we add print statements to stdout that give some sort of reason when Parceive does not generate any events, such as "FAILURE: invalid database input" or "FAILURE: database missing feature X"?

**Comment by pdigiglio** [comment]
Can you please tell me which commit you're working on and how can I reproduce your problem? By the way, did you check the log file?

**Comment by deknapp** [comment]
I'm working on the latest commit from the parasite branch. To reproduce the problem, compile this commit and run ./pcv swaptions.db. I'll send you this database now. 

No, I didn't. I will now.

**Comment by deknapp** [comment]
Ok, there is no log file, must have been added in a later commit. I'll try pulling the changes so I can look at it.

**Comment by pdigiglio** [comment]
I get a segmentation fault from `ParasiteTracker::bottomThread` on the commit you indicated me (namely, _3e140e1_) and the log file _SAAP.log_ is empty. Anyway, I'd say that the database is valid because it is correctly read using the code in the _development_ branch (_f282918_).

I suggest that you try to merge _development_ into _parasite_ (not the other way round) and let me know if you have the same problem.

**Comment by pdigiglio** [comment]
I just realized that a file had not been pushed in the _development_ branch. Please use _11e9a6b_.

**Comment by deknapp** [comment]
OK, I will merge back into that commit once I fix conflicts on my end.
