### ISSUE TITLE
error: member access into incomplete type 'const CallInfo'

### ISSUE THREAD

**Issue by deknapp** [wilhelma/pcvInterpreter#32]
@pdigiglio 
Line 150: ParasiteTool.cpp :  last_event_time = _info->callTime;
There are two CallInfo header files, and I think I'm getting this error because I am not using the right one. I am getting the same error for all other Info structures. In which file should I change the include statement? 
To reproduce the error, make my commit 2fbb538.

**Comment by deknapp** [comment]
Solved by #include-ing Info header files directly in ParasiteTool.h. I don't understand why this is necessary because of the new changes, but it works.

**Comment by pdigiglio** [comment]
There are two _CallInfo.h_ header files because one of them is a forward header. I use the forward headers to minimize compilation dependencies.

Probably you got the error message because you were relying on _CallInfo.h_ being included in another header file that you included in _ParasiteTool.h_. Each file should include all the headers it needs to compile (and not more than those). If you don't need to access the "internal structure" of the classes, i.e. you only need their name available, the right choice is most probably to include the forward header. For example:

``` cpp
/// @file include/MyCallInfoWrapper.h

#include "fwd/CallInfo.h" // fwd header: no need to access CallInfo's structure
#include "Types.h"

class MyCallInfoWrapper {
public:
    MyCallInfoWrapper(const CallInfo* call_info) : Info_(call_info) {}
    CAL_ID getId() const;
private:
    const CallInfo* Info_;
};
```

``` cpp
/// @file src/MyCallInfoWrapper.cpp

#include "CallInfo.h" // now you need to access its member variables
#include "MyCallInfoWrapper.h"
#include "Types.h"

CAL_ID MyCallInfoWrapper::getId() const
{ return Info_->id; }
```

Anyway, I think the solution would have been `#include`ing _CallInfo.h_ in _ParasiteTool.cpp_ and _fwd/CallInfo.h_ in _ParasiteTool.h_.

**Comment by deknapp** [comment]
OK, when I have time, I will go in and alter all the header files in Parasite according to this pattern, where it works.
