### ISSUE TITLE
noexcept specifier

### ISSUE THREAD

**Issue by pdigiglio** [wilhelma/pcvInterpreter#35]
I suggest we use the `noexcept` specifier for every function from which no exception propagates. This means that:
- The function itself mustn't `throw`;
- If the function calls another function that may throw, it has to `try` and `catch` the exception of the called function.

We should be particularly careful that destructors _never_ throw!

@wilhelma What was your problem with `noexcept`?

**Comment by wilhelma** [comment]
@pdigiglio
For example: 
`explicit EventService() noexcept =default;`

This leads to the following error:
`/home/wilhelma/workspace/pcvInterpreter/include/EventService.h:37: ‘EventService::EventService() noexcept’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘noexcept (<uninstantiated>)’
     explicit EventService() noexcept = default;
              ^`

Without noexcept I get no error.
